#!/bin/bash

# set up integers

declare -i DETECTIONS
declare -i DEVICES
declare -i MAXSCANS
declare -i SCAN

DETECTIONS=0
DEVICES=0
MAXSCANS=10
SCAN=0

# output to screen

SCREEN=false

# configure log path

LOGPATH="/var/log/gyrid"

# set the log files

# files are named using the date at run time

DETECTIONLOG="${LOGPATH}/detection.log"
DEVICELOG="${LOGPATH}/device.log"
SCRIPTLOG="${LOGPATH}/gyrid.log"

# remember when the script started

START=`date +%Y-%m-%d\ %H:%M:%S`

# create log path if it doesn't exist

if [ ! -d ${LOGPATH} ]
then
  mkdir ${LOGPATH}
fi

# create log files if they doesn't exist

if [ ! -e ${SCRIPTLOG} ]
then
  touch ${SCRIPTLOG}
  echo "${START} Script log ${SCRIPTLOG} created" >> ${SCRIPTLOG}
else
  echo "${START} Script log ${SCRIPTLOG} exists" >> ${SCRIPTLOG}
fi

if [ ! -e ${DETECTIONLOG} ]
then
  touch ${DETECTIONLOG}
  echo "${START} Detection log ${DETECTIONLOG} created" >> ${SCRIPTLOG}
fi

if [ ! -e ${DEVICELOG} ]
then
  touch ${DEVICELOG}
  echo "${START} Device log ${DEVICELOG} created" >> ${SCRIPTLOG}
else
  echo "${START} Device log ${DEVICELOG} exists" >> ${SCRIPTLOG}
fi

echo "${START} GYRID Bluetooth scanner started" >> ${SCRIPTLOG}

# scan

#while [ ${SCAN} -lt ${MAXSCANS} ]
while [ 1 ]
do

  # find out how many detections have been made so far

  DETECTIONS=`wc -l ${DETECTIONLOG} | awk '{print $1}'`

  DEVICES=`wc -l ${DEVICELOG} | awk '{print $1}'`

  SCAN=$((SCAN + 1))

  # remember when the scan started

  TIME=`date +%Y-%m-%d\ %H:%M:%S`

  # update the screen

  if [ ${SCREEN} = true ]
  then

    clear

    echo "                                                                BLUETOOTH SCANNER"
    echo "================================================================================="
    echo "Detection log   ${DETECTIONLOG}"
    echo "Device log      ${DEVICELOG}"
    echo "Scan interval   10s"
    echo "Maximum scans   ${MAXSCANS}"
    echo "Scanner started ${START}"
    echo "---------------------------------------------------------------------------------"
    echo "Scan            ${SCAN}"
    echo "Started at      ${TIME}"
    echo "Devices         ${DEVICES}"
    echo "Detections      ${DETECTIONS}"
    echo "                                                          Ctrl+C to stop scanning"

  fi

  # scan

  while read DEVICE
  do

    # ignore the first line of hcitool's output

    if [ "${DEVICE}" != "Scanning ..." ]
    then

      # isolate the device address

      ADDR=$(echo "${DEVICE}" | awk '{print $1}')

      # isolate the device name

      NAME=$(echo "${DEVICE}" | sed "s/^.*${ADDR}\t//")

      echo "${TIME} Device ${ADDR} detected with name ${NAME}" >> ${SCRIPTLOG}

      # update the detections log

      echo "${TIME},${ADDR}" >> ${DETECTIONLOG}

      # update the devices log if this is a new device

      if ! grep -q "${ADDR}" "${DEVICELOG}"
      then

        echo "${ADDR},${NAME}" >> ${DEVICELOG}

      fi

    fi # end of hcitool output loop

  done <<< "`hcitool scan --flush`" # end of scan

done

exit 0
